export const REFRESH_DB_STATE = "REFRESH_DB_STATE";
export const NEW_DB_FROM_FILE = "NEW_DB_FROM_FILE";
export const TABLELAND_IMPORT = "TABLELAND_IMPORT";
export const GENERIC_QUERY = "GENERIC_QUERY";
export const GENERIC_QUERY_RESPONSE = "GENERIC_QUERY_RESPONSE";
